### ISSUE TITLE
Edit company

### ISSUE THREAD

**Issue by ramlaxmi** [ramlaxmi/seyon-ui#37]
check if GST registered? dont mandate? if not registered 
dont show GSTs in print invoice 
Dont select SAC Code at the time of profomo /invoice
hide SAC code in print invoice

**Comment by bbroko** [comment]
check if GST registered? dont mandate? if not registered -- done
Dont select SAC Code at the time of profomo /invoice -- done

**Comment by bbroko** [comment]
hide SAC code in print invoice
dont show GSTs in print invoice
